spring:
  datasource:
    testWhileIdle: true
    validationQuery: select 1
    initialize: false
    url: jdbc:mysql://localhost:3306/retail_test?useUnicdoe=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    sql-script-encoding: utf-8